export const RABBITMQ_MODULE_OPTIONS = 'RABBITMQ_MODULE_OPTIONS';

export const RABBITMQ_CONNECTION_MANAGER = 'RABBITMQ_CONNECTION_MANAGER';

export const RABBITMQ_SUBSCRIBE_METADATA = 'RABBITMQ_SUBSCRIBE_METADATA';

export const RABBITMQ_SERVICE_DISCOVERY = 'RABBITMQ_SERVICE_DISCOVERY';

export const DEFAULT_CONNECTION_NAME = 'default';
